### ISSUE TITLE
[Epic] Do preliminary research for online resources for 500 datasets (Sprint 4 June 2018)

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#165]
Description

The task is to find and collect datasets from various online resources. In order to collect 500 of them, we give precedence to those online resources that have multiple interesting datasets available for free. The current task for all is to once they find a prospective resource, do a preliminary analysis and determine how many datasets they can extract and provide an estimated time of completion (from here on referred to as **ETC**).

Info about analysis should be written in this spreadsheet in a sheet that matches your name
https://docs.google.com/spreadsheets/d/1eHndEgHJH1RYhLQVgfXRtvcnEbgHagM5y4pxPmvDJkU/edit#gid=1415064890

## Acceptance criteria

* [x] we have done research and identified sources of datasets that we'll use to scrape/wrangle datasets

## Tasks

**Comment by Branko-Dj** [comment]
Research is completed and results can be found in the aforementioned spreadsheet
