### ISSUE TITLE
Create datahubio/issues repo for reporting bugs and suggesting features 

### ISSUE THREAD

**Issue by rufuspollock** [datahubio/datahub-v2-pm#5]
Create here https://github.com/datahubio/issues

Issues only repo.

Create a simple README with logo nicely and tell people briefly what it is for and how to an open an issue.

**Comment by Mikanebu** [comment]
https://github.com/datahubio/qa

**Comment by rufuspollock** [comment]
This is not yet FIXED. We don't have a README or any instructions for people who arrive there.

**Comment by rufuspollock** [comment]
FIXED. We have the issue tracker and a nice README.
