### ISSUE TITLE
Blog post re Data Validation support

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#71]
## Acceptance criteria

* [ ] a blog post about data validation support at https://datahub.io/blog/data-validation-in-the-datahub

## Tasks

* [x] Plan
* [x] Write
* [x] Review by 2 team members
* [x] Refactor
* [x] Publish

**Comment by zelima** [comment]
@anuveyatsu what's left here?

**Comment by anuveyatsu** [comment]
@zelima currently working on that. We'll publish it today/tomorrow.

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/blog/data-validation-in-the-datahub
