### ISSUE TITLE
Remove preparation section from README on Datahub 

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#91]
Some core datasets have the instruction of how to download, run script and what language to use to run the script... The same section on datahub does not make any sense, as you don't have to run any script to process the data.

Several examples:
* finance VIX https://github.com/datasets/finance-vix#preparation
* bonds US https://github.com/datasets/bond-yields-us-10y#preparation
* bonds UK https://github.com/datasets/bond-yields-uk-10y#preparation
* airport odes https://datahub.io/core/airport-codes#preparation

## Acceptace criteria

* [x] preparation section is removed from the abovementioned datasets

## Tasks

* [x] remove preparation section from readme in `flow.yml`

**Comment by zelima** [comment]
@Mikanebu could you please take care of this

**Comment by anuveyatsu** [comment]
@zelima the only way to fix this is to have different README in the `flow.yaml` - wdyt? cc/ @Mikanebu

**Comment by Mikanebu** [comment]
@anuveyatsu @zelima I will fix it right now

**Comment by Mikanebu** [comment]
FIXED, removed `preparation` section from the following datasets(only from descriptor)
* https://datahub.io/core/finance-vix
* https://datahub.io/core/bond-yields-uk-10y
* https://datahub.io/core/bond-yields-us-10y
* https://datahub.io/core/airport-codes
